eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8801/eureka/

server:
  port: 8809

spring:
  application:
    name: service-hi

ribbon:
  eureka:
    enabled: true

