eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8801/eureka/

server:
  port: 5555

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true  //打开feign中的hystrix(断路由 feign自己集成了hystrix)

